#!/usr/bin/env php
<?php

use SPSOstrov\AppConsole\App;

$rootDir = getenv("SPSO_APP_DIR");
$autoload = $rootDir . "/vendor/autoload.php";
require_once($autoload);

array_shift($argv);

if (count($argv) > 1) {
    fprintf(STDERR, "Error: invalid help invocation (maybe a bug?)\n");
}

$command = $argv[0] ?? null;

$args = [];
$args[] = getenv("SPSO_APP_ARGV0");

if ($command !== null) {
    $args[] = '--';
    $args[] = $command;
}
$args[] = '--help';

$app = new App($rootDir . "/vendor/composer");
exit($app->run($args));
